### ISSUE TITLE
Different result of rendering .md page on Wiki and on repo preview

### ISSUE THREAD

**Issue by kiddick** [primer/primer-markdown#68] opened 2017-04-16 20:24 UTC
Not sure is it right place for that bug. But there is issue with rendering list of links with images:

wiki:
https://github.com/kiddick/draft/wiki/Pip

repo:
https://github.com/kiddick/pystuff/blob/master/pyvideos/README.md

content is identical

**Comment by shurcooL** [comment] 2017-04-17 00:50
It looks different only because the width of a README is different from the width of a wiki page. The wiki page is narrower because of the sidebar on the right.

If you were to make them same width, they render identically:

![image](https://cloud.githubusercontent.com/assets/1924134/25075612/45c3d598-22e6-11e7-9649-9f43d6edba00.png)

**Comment by sophshep** [comment] 2017-05-23 22:04
Hi @kiddick - I think what is happening is that the link is an inline element, so when the container is wide enough, it is positioned inline with the list item. To prevent this, you can add a linebreak in your markdown file.

This is expected behavior, so I'm closing the issue.

**Closed by sophshep** 2017-05-23 22:04 UTC
